### ISSUE TITLE
Segmentation fault after start

### ISSUE THREAD

**Issue by alexhofstaetter** [gmsoft-tuxicoman/pom-ng#10]
Hello!

Unfortunately i have a little problem. I got pom-ng installed correct. When i start it, it starts the webserver, when i try to connect via the web (or the console) pom gets a segfault and crashes.

So I compiled it with debug infos and ran it in gdb. See the log down there. Have you any ideas why pom-ng is crashing?

main: Starting pom-ng v0.0.18 ...
core: Starting 1 processing thread(s)
httpd: HTTP daemon started on 0.0.0.0, port 8080
httpd: HTTP daemon started on ::, port 8080
main: pom-ng started ! You can now connect using pom-ng-console or the web-ui.
registry: Configuration "startup" not found in the database
Segmentation fault (core dumped)

Full gdb log:

Starting program: /usr/local/bin/pom-ng -d 5
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
main: Starting pom-ng v0.0.18 ...
ptype: Ptype of type string not found, trying to load module
mod: Module ptype_string loaded, registering components ...
ptype: Registering ptype string
ptype: Ptype of type uint32 not found, trying to load module
mod: Module ptype_uint32 loaded, registering components ...
ptype: Registering ptype uint32
pload: Registered payload type javascript : class application, extension .js
pload: Registered payload type json : class application, extension .json
pload: Registered payload type msword : class document, extension .doc
pload: Registered payload type binary : class other, extension .bin
pload: Registered payload type pdf : class document, extension .pdf
pload: Registered payload type excel : class document, extension .xls
pload: Registered payload type powerpoint : class document, extension .ppt
pload: Registered payload type rar : class application, extension .rar
pload: Registered payload type swf : class application, extension .swf
pload: Registered payload type form-urlencoded : class other, extension .txt
pload: Registered payload type jpeg : class image, extension .jpg
pload: Registered payload type gif : class image, extension .gif
pload: Registered payload type png : class image, extension .png
pload: Registered payload type flv : class video, extension .flv
pload: Registered payload type webm : class video, extension .webm
pload: Registered payload type m2ts : class video, extension .m2ts
pload: Registered payload type rfc822 : class document, extension .txt
pload: Registered payload type text : class document, extension .txt
pload: Registered payload type multipart : class other, extension .multipart
pload: Registered payload type sdp : class other, extension .sdp
pload: Registered payload type dtmf : class other, extension .dtmf
pload: Registered payload type g711a : class audio, extension .alaw
pload: Registered payload type g711u : class audio, extension .ulaw
pload: Registered payload type g723 : class audio, extension .g723
pload: Registered payload type g729 : class audio, extension .g729
pload: Registered payload type html : class other, extension .html
pload: Mime type application/javascript registered as javascript
pload: Mime type application/json registered as json
pload: Mime type application/msword registered as msword
pload: Mime type application/octet-stream registered as binary
pload: Mime type application/octetstream registered as binary
pload: Mime type application/pdf registered as pdf
pload: Mime type application/vnd.ms-excel registered as excel
pload: Mime type application/vnd.ms-powerpoint registered as powerpoint
pload: Mime type application/x-javascript registered as javascript
pload: Mime type application/x-json registered as json
pload: Mime type application/x-rar-compressed registered as rar
pload: Mime type application/x-shockwave-flash registered as swf
pload: Mime type application/x-www-form-urlencoded registered as form-urlencoded
pload: Mime type image/jpeg registered as jpeg
pload: Mime type image/jpg registered as jpeg
pload: Mime type image/gif registered as gif
pload: Mime type image/png registered as png
pload: Mime type video/x-flv registered as flv
pload: Mime type video/webm registered as webm
pload: Mime type video/mp2t registered as m2ts
pload: Mime type message/rfc822 registered as rfc822
pload: Mime type text/plain registered as text
pload: Mime type multipart/mixed registered as multipart
pload: Mime type multipart/digest registered as multipart
pload: Mime type multipart/message registered as multipart
pload: Mime type multipart/parallel registered as multipart
pload: Mime type multipart/alternative registered as multipart
pload: Mime type multipart/related registered as multipart
pload: Mime type multipart/report registered as multipart
pload: Mime type multipart/signed registered as multipart
pload: Mime type multipart/encrypted registered as multipart
pload: Mime type multipart/form-data registered as multipart
pload: Mime type application/sdp registered as sdp
pload: Mime type application/dtmf registered as dtmf
pload: Mime type application/dtmf-relay registered as dtmf
pload: Mime type audio/pcma registered as g711a
pload: Mime type audio/pcmu registered as g711u
pload: Mime type audio/g723 registered as g723
pload: Mime type audio/g729 registered as g729
pload: Mime type text/html registered as html
mod: Module ptype_uint16 loaded, registering components ...
ptype: Registering ptype uint16
mod: Module ptype_timestamp loaded, registering components ...
ptype: Registering ptype timestamp
mod: Module proto_http loaded, registering components ...
event: Event http_query registered
event: Event http_response registered
proto: Proto http registered
mod: Module ptype_bytes loaded, registering components ...
ptype: Registering ptype bytes
mod: Module ptype_uint8 loaded, registering components ...
ptype: Registering ptype uint8
mod: Module proto_ppp_chap loaded, registering components ...
event: Event ppp_chap_challenge_response registered
event: Event ppp_chap_success_failure registered
proto: Proto ppp_chap registered
mod: Module proto_udp loaded, registering components ...
proto: Proto udp registered
mod: Module ptype_ipv6 loaded, registering components ...
ptype: Registering ptype ipv6
mod: Module ptype_mac loaded, registering components ...
ptype: Registering ptype mac
mod: Module proto_80211 loaded, registering components ...
proto: Proto 80211 registered
mod: Module proto_ethernet loaded, registering components ...
proto: Proto ethernet registered
mod: Module ptype_bool loaded, registering components ...
ptype: Registering ptype bool
mod: Module proto_docsis loaded, registering components ...
proto: Proto docsis_mgmt registered
proto: Proto docsis registered
mod: Module ptype_ipv4 loaded, registering components ...
ptype: Registering ptype ipv4
mod: Module proto_ipv4 loaded, registering components ...
proto: Proto ipv4 registered
mod: Module proto_mpeg loaded, registering components ...
proto: Proto mpeg_dvb_mpe registered
proto: Proto mpeg_sect registered
proto: Proto mpeg_ts registered
mod: Module proto_ppi loaded, registering components ...
proto: Proto ppi registered
mod: Module proto_radiotap loaded, registering components ...
proto: Proto radiotap registered
mod: Module input_pcap loaded, registering components ...
input: Registering input pcap_interface
input: Registering input pcap_file
input: Registering input pcap_dir
mod: Module proto_eap loaded, registering components ...
event: Event eap_identity registered
event: Event eap_md5_challenge registered
event: Event eap_success_failure registered
proto: Proto eap registered
mod: Module analyzer_eap loaded, registering components ...
event: Event eap_md5_auth registered
analyzer: Analyzer eap registered
mod: Module proto_tcp loaded, registering components ...
proto: Proto tcp registered
mod: Module proto_dns loaded, registering components ...
proto: Proto dns registered
mod: Module analyzer_dns loaded, registering components ...
event: Event dns_record registered
analyzer: Analyzer dns registered
mod: Module analyzer_tftp loaded, registering components ...
event: Event tftp_file registered
analyzer: Analyzer tftp registered
mod: Module proto_ppp_pap loaded, registering components ...
event: Event ppp_pap_request registered
event: Event ppp_pap_ack_nack registered
proto: Proto ppp_pap registered
mod: Module analyzer_ppp_pap loaded, registering components ...
event: Event ppp_pap_auth registered
analyzer: Analyzer ppp_pap registered
mod: Module proto_ppp loaded, registering components ...
proto: Proto ppp registered
mod: Module ptype_uint64 loaded, registering components ...
ptype: Registering ptype uint64
mod: Module output_pcap loaded, registering components ...
output: Registering output pcap_file
output: Registering output pcap_flow
event: Event pcap_flow_file registered
mod: Module proto_rtp loaded, registering components ...
proto: Proto rtp registered
mod: Module input_kismet loaded, registering components ...
input: Registering input kismet_drone
mod: Module output_file loaded, registering components ...
output: Registering output file
mod: Module analyzer_sdp loaded, registering components ...
analyzer: Analyzer sdp registered
mod: Module input_dvb loaded, registering components ...
input: Registering input dvb_device
input: Registering input dvb_c
event: Event dvb_status registered
input: Registering input dvb_s
input: Registering input dvb_atsc
input: Registering input docsis
input: Registering input docsis_scan
event: Event docsis_scan_stream registered
mod: Module proto_arp loaded, registering components ...
proto: Proto arp registered
mod: Module proto_vlan loaded, registering components ...
proto: Proto vlan registered
mod: Module analyzer_arp loaded, registering components ...
event: Event arp_new_sta registered
event: Event arp_sta_changed registered
analyzer: Analyzer arp registered
mod: Module decoder_base64 loaded, registering components ...
decoder: Registering decoder base64
mod: Module proto_icmp loaded, registering components ...
proto: Proto icmp registered
mod: Module proto_icmp6 loaded, registering components ...
proto: Proto icmp6 registered
mod: Module analyzer_http loaded, registering components ...
event: Event http_request registered
analyzer: Analyzer http registered
mod: Module proto_pppoe loaded, registering components ...
proto: Proto pppoe registered
mod: Module analyzer_ppp_chap loaded, registering components ...
event: Event ppp_chap_mschapv2_auth registered
event: Event ppp_chap_md5_auth registered
analyzer: Analyzer ppp_chap registered
mod: Module decoder_quoted_printable loaded, registering components ...
decoder: Registering decoder quoted-printable
mod: Module analyzer_rfc822 loaded, registering components ...
analyzer: Analyzer rfc822 registered
mod: Module output_tap loaded, registering components ...
output: Registering output tap
mod: Module decoder_percent loaded, registering components ...
decoder: Registering decoder percent
mod: Module analyzer_multipart loaded, registering components ...
analyzer: Analyzer multipart registered
mod: Module proto_sip loaded, registering components ...
event: Event sip_req registered
event: Event sip_rsp registered
proto: Proto sip registered
mod: Module analyzer_sip loaded, registering components ...
event: Event sip_call registered
event: Event sip_call_dial registered
event: Event sip_call_ringing registered
event: Event sip_call_connect registered
event: Event sip_call_hangup registered
event: Event sip_dtmf registered
analyzer: Analyzer sip registered
mod: Module analyzer_rtp loaded, registering components ...
event: Event rtp_stream registered
analyzer: Analyzer rtp registered
mod: Module proto_smtp loaded, registering components ...
event: Event smtp_cmd registered
event: Event smtp_reply registered
proto: Proto smtp registered
mod: Module analyzer_smtp loaded, registering components ...
event: Event smtp_msg registered
event: Event smtp_auth registered
analyzer: Analyzer smtp registered
mod: Module proto_ipv6 loaded, registering components ...
proto: Proto ipv6 registered
mod: Module output_log loaded, registering components ...
output: Registering output log_txt
output: Registering output log_xml
mod: Module analyzer_docsis loaded, registering components ...
event: Event docsis_cm_new registered
event: Event docsis_cm_reg_status registered
analyzer: Analyzer docsis registered
mod: Module proto_gre loaded, registering components ...
proto: Proto gre registered
mod: Module analyzer_dtmf loaded, registering components ...
analyzer: Analyzer dtmf registered
mod: Module proto_tftp loaded, registering components ...
proto: Proto tftp registered
mod: Module analyzer_png loaded, registering components ...
analyzer: Analyzer png registered
mod: Module datastore_sqlite loaded, registering components ...
datastore: Registering datastore sqlite
mod: Module analyzer_gif loaded, registering components ...
analyzer: Analyzer gif registered
mod: Module proto_8021x loaded, registering components ...
proto: Proto 8021x registered
mod: Module output_inject loaded, registering components ...
output: Registering output inject
core: Starting 1 processing thread(s)
[New Thread 0x7fffeaca4700 (LWP 25561)]
[New Thread 0x7fffea4a3700 (LWP 25562)]
httpd: HTTP daemon started on 0.0.0.0, port 8080
[New Thread 0x7fffe9ca2700 (LWP 25563)]
httpd: HTTP daemon started on ::, port 8080
datastore_sqlite: New connection to database ~/.pom-ng/sys_datastore.db
datastore_sqlite: READ QUERY : SELECT pkid, name, description FROM datasets
datastore_sqlite: WRITE QUERY : INSERT INTO datasets ( name, description ) VALUES ( ?, ? )
datastore_sqlite: DELETE QUERY : DELETE FROM datasets
datastore_sqlite: READ QUERY : SELECT pkid, dataset_id, name, type, field_id FROM dataset_schema
datastore_sqlite: WRITE QUERY : INSERT INTO dataset_schema ( dataset_id, name, type, field_id ) VALUES ( ?, ?, ?, ? )
datastore_sqlite: DELETE QUERY : DELETE FROM dataset_schema
datastore_sqlite: READ QUERY : SELECT pkid, name, timestamp FROM config_list
datastore_sqlite: WRITE QUERY : INSERT INTO config_list ( name, timestamp ) VALUES ( ?, ? )
datastore_sqlite: DELETE QUERY : DELETE FROM config_list
datastore: Datastore sqlite opened
main: pom-ng started ! You can now connect using pom-ng-console or the web-ui.
registry: Configuration "startup" not found in the database
[New Thread 0x7fffe94a1700 (LWP 25564)]
[New Thread 0x7fffe8ca0700 (LWP 25565)]
[New Thread 0x7fffe3fff700 (LWP 25566)]
[New Thread 0x7fffe37fe700 (LWP 25567)]
[New Thread 0x7fffe2ffd700 (LWP 25568)]
[New Thread 0x7fffe27fc700 (LWP 25569)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe94a1700 (LWP 25564)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt full
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
No locals.
#1  0x000000000040bfd7 in xmlrpcsrv_process (
    data=0x7fffd8001dd0 "<methodCall><methodName>core.getVersion</methodName><params/></methodCall>", size=74, response=0x7fffe94a0b40, 
    reslen=0x7fffe94a0b38) at xmlrpcsrv.c:86
        env = {fault_occurred = 0, fault_code = 0, fault_string = 0x0}
        output = 0x7fffd8001b80
#2  0x0000000000407533 in httpd_mhd_answer_connection (cls=0x0, connection=0x7fffdc0008c0, url=0x7fffdc000a85 "/RPC2", 
    method=0x7fffdc000a80 "POST", version=0x7fffdc000a8b "HTTP/1.1", upload_data=0x0, upload_data_size=0x7fffe94a0c50, 
    con_cls=0x7fffdc000918) at httpd.c:316
        xml_response = 0x7fffd8002760 "\b\002"
        xml_reslen = 153
        response = 0x0
        mime_type = 0x0
        status_code = 200
        info = 0x7fffd80008c0
        admin_passwd = 0x0
#3  0x00007ffff66abf71 in ?? () from /usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10
No symbol table info available.
#4  0x00007ffff66ad428 in ?? () from /usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10
No symbol table info available.
#5  0x00007ffff66b0ee1 in ?? () from /usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10
No symbol table info available.
#6  0x00007ffff6c2d0a4 in start_thread (arg=0x7fffe94a1700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7fffe94a1700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737107334912, 7886725835823449988, 1, 140737354125408, 140736884377792, 
                140737107334912, -7886764158247041148, -7886740998213269628}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007ffff5b7b04d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

**Comment by alexhofstaetter** [comment]
In addition i need to say that i built pom-ng on a fresh ubuntu install. I got an segfault with the same error message

**Comment by alexhofstaetter** [comment]
problem solved: use the right packages ...
get "libxmlrpc-core-c3-dev" from the apt repos :)
